NEW: option to hide checkmarks in menu when items has an icon (closer…
randrew/phantomstyle pull request #9
Opened 2019-12-17 20:51 UTC by neFAST

… to standard windows style)

![image](https://user-images.githubusercontent.com/182520/71033312-64f58d80-2117-11ea-9d6b-3781a83ce1c0.png)

2019-12-19 05:49 UTC, randrew requested changes
This is a good idea! Could you run this through clang-format? I see some lines of code that were changed unnecessarily due to whitespace and formatting. After you've done that, I will go through and make some tweaks.

2019-12-19 07:05 UTC, neFAST commented
Oops some of my specular branch went in this PR, I will clean this up

2019-12-19 09:41 UTC, randrew commented
No rush :)

2019-12-27 01:44 UTC, randrew commented
OK, thanks for fixing the formatting issues.

I've taken a look at your changes. There are a few problems. Let's start with the first.

The checkmark appearance in menu items has been affected by your change. They are no longer correctly sized or aligned.

Here is how the "Charlie" menu appears in the "funhouse" example project before your changes:

![funhouse_NlBvEWPCBg](https://user-images.githubusercontent.com/26056/71496253-aca5b300-2895-11ea-8543-156fd6707a72.png)

But here it is after your changes:

![funhouse_B5hNEDiZbA](https://user-images.githubusercontent.com/26056/71496267-c1824680-2895-11ea-8b91-37bf2255d82e.png)

2019-12-29 12:13 UTC, neFAST commented
Hum I locally changed the shape of the checks (don't take it personally, I really like phantom but the menus don't look good to me, the margins are too small and it's much narrower than what we're used too on windows)
I could revert this in my commit, but as you said there are other issues. Like for this to work, I think we need to have the check/radio width equal the icon width, otherwise we need at least the check/radio to be centered within the space left for the icons

2019-12-29 20:20 UTC, neFAST commented
I think it's much better now, can you detail the other issues you found?

2019-12-30 03:34 UTC, randrew commented
Sorry, I'm busy right now. It will take me a few days to get to this.

2020-01-08 21:43 UTC, JulienMaille commented
No problem, let me know if I can help.

2025-06-11 06:30 UTC, closed without merging